repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-toml
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: requirements-txt-fixer
          - id: trailing-whitespace
            # bump2version produces whitespace in setup.cfg, so exclude to
            # not inferfere with versioning
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.7.0
      hooks:
          - id: ruff
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.12.1
      hooks:
          - id: mypy
            additional_dependencies:
                - types-setuptools
                - types-PyYAML
