#!/bin/bash

#SBATCH -p cpu # partition (queue)
#SBATCH -N 1   # number of nodes
#SBATCH --mem 64G # memory pool for all cores
#SBATCH -n 10 # number of cores
#SBATCH -t 2-00:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-type=ALL
#SBATCH --mail-user=l.porta@ucl.ac.uk

# Load the RSP_vision module
module load miniconda
conda activate /nfs/nhome/live/lporta/micromamba/envs/rsp

# Run the training script generated by SLEAP
python3 batch_analysis.py