import logging

from .parser import Parser


class ChryssanthiParser(Parser):
    """Parser for Chryssanthi's data, based on the folder structure Winstor
    server. Inherits from Parser.

    :param folder_name: name of the folder containing the experimental data
    generated by suite2p and registers2p. Initialized in the parent class.
    :type folder_name: str

    :param mouse_line: name of the mouse line, e.g. AS, CX, etc.
    :type mouse_line: str
    :param mouse_id: id of the mouse, e.g. 95_2
    :type mouse_id: str
    :param hemisphere: hemisphere of the brain, e.g. hL, hR
    :type hemisphere: str
    :param brain_region: brain region, e.g. V1, V2, etc.
    :type brain_region: str
    :param monitor_position: position of the monitor, e.g. monitor_front
    :type monitor_position: str
    :param fov: field of view, e.g. FOV3c
    :type fov: str
    :param cre: cre line, e.g. cre-off
    :type cre: str
    """

    def __init__(self, folder_name: str) -> None:
        """Constructor method"""
        super().__init__(folder_name)

    def parse(self) -> None:
        """Parses the folder name and evaluates the parameters `mouse_line`,
        `mouse_id`, `hemisphere`, `brain_region`, `monitor_position, `fov`
        and `cre`. It is specific to Chrissanthi's data.

        :raises NotImplementedError: if there is not the implementation for
         a specific folder structure
        :raises RuntimeError: if the parser failed in identifying the
        parameter `monitor_position`
        """

        splitted = self.folder_name.split("_")
        self.mouse_line = splitted[0]
        self.subfolder_exists = False

        if splitted[1].startswith("111"):
            self.mouse_id = splitted[1]
            self.hemisphere = splitted[2]
            self.brain_region = splitted[3]

        else:
            self.mouse_id = splitted[1] + "_" + splitted[2]

            if (self.mouse_line == "AS" and self.mouse_id == "95_2") or (
                self.mouse_line == "CX" and int(splitted[1]) < 61
            ):
                self.subfolder_exists = True
                logging.warning(
                    f"Experimental data without parsing implementation: \
                    {self.folder_name}"
                )
                raise NotImplementedError(
                    "Unclear data structure, contains subfolder"
                )

            self.hemisphere = splitted[3]
            self.brain_region = splitted[4]

        for item in splitted:
            if "FOV" in item:
                self.fov = item
            if "cre" in item:
                self.cre = item
            if "monitor" == item:
                self.monitor_position = item
            if hasattr(self, "monitor_position"):
                self.monitor_position += item

        if "monitor" not in self.monitor_position:
            logging.error(
                "Monitor position not found in folder name",
                extra={"ChryssanthiParser": self},
            )
            logging.debug(self.monitor_position)
            raise RuntimeError("Monitor position not found in folder name")
