from abc import ABC, abstractmethod


class Parser(ABC):
    """Abstract base class for parsers. Child classes must be project
    specific and tailor made to the folder structure in Winstor.
    When inheriting from this class, the method parse() must be implemented.

    :param folder_name: name of the folder containing the experimental
    data generated by suite2p and registers2p
    :type folder_name: str
    """

    def __init__(self, folder_name: str) -> None:
        """Constructor method"""
        self.folder_name = folder_name
        self.parse()

    @abstractmethod
    def parse(self) -> None:
        """Parses the folder name and evaluates the parameters `mouse_line`,
        `mouse_id`, `hemisphere`, `brain_region`, `monitor_position, `fov`
        and `cre`. To be implemented by the child classes taking into account
        the folder structure of each project.
        """
        pass
