parser: Parser2pRSP

server: 'ssh.swc.ucl.ac.uk'

paths:
  winstor: '/Volumes/winstor/'
  imaging: '/Volumes/winstor/swc/margrie/Chryssanthi/imaging'
  allen-dff: '/Volumes/winstor/swc/margrie/Chryssanthi/imaging/allen_dff'
  serial2p: '/Volumes/winstor/swc/margrie/Chryssanthi/imaging/serial2p'
  stimulus-ai-schedule: '/Volumes/winstor/swc/margrie/Chryssanthi/imaging/stimulus_AI_schedule_files'

use-allen-dff: true
analysis-type: 'sf_tf'
