scientist: Chryssanthi

analysis-specific-configs:
  analysis-type: ['retinotopy', 'sftf', 'sparse_noise']
  region-id: AS_1111877_hL_V1_monitor_front # there are very many combinations - ask chrissanthy
  fluorescence_type: ['df', 'allen_df']

server: 'ssh.swc.ucl.ac.uk'

paths:
  winstor: '/Volumes/winstor/'
  imaging: '/Volumes/margrie/Chryssanthi/imaging/'
